import type { Metadata } from 'next';
import { Inter, Titillium_Web } from 'next/font/google';
import './globals.css';
import Header from './_components/header/Header';

const titilium = Titillium_Web({ weight: ['300', '400', '600', '700'], subsets: ['latin'] });
// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={titilium.className}>
				<Header />
				<div className="page-wrap">{children}</div>
			</body>
		</html>
	);
}
